# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('etox', ['internet', 'network'])
    module.source = [
		'model/link-state-header.cc',
		'model/link-state-routing-protocol.cc',
		'model/link-state-node.cc',
		'model/BHeap.cc',
		'model/Dijkstra.cc',
        'helper/link-state-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('etox')
    module_test.source = [
        'test/etox-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'etox'
    headers.source = [
		'model/link-state-repo.h',
		'model/link-state-header.h',
		'model/link-state-routing-protocol.h',
		'model/link-state-node.h',
		'model/BHeap.h',
		'model/Dijkstra.h',
		'helper/link-state-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

